name: Release Kratix CLI
on:
  workflow_dispatch:
    inputs:
      manual_version:
        required: false
  push:
    tags:
      - 'v*'

jobs:
  make-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
          check-latest: true
      - name: Install goreleaser
        run: |
          curl -sLo goreleaser.tar.gz https://github.com/goreleaser/goreleaser-pro/releases/download/v2.3.2-pro/goreleaser-pro_Linux_x86_64.tar.gz
          tar -xzf goreleaser.tar.gz goreleaser
          sudo mv goreleaser /usr/local/bin/goreleaser
          chmod +x /usr/local/bin/goreleaser
          rm goreleaser.tar.gz
      - name: Run make release
        run: |
          set -ex
          if [ -n "$MANUAL_VERSION" ]; then
            echo "this workflow is triggered with manual version"
            export VERSION="${MANUAL_VERSION}"
            git fetch --tags origin
            git checkout tags/${VERSION}
          fi
          echo "releasing"
          echo $VERSION
          gh config set prompt disabled
          make release
          gh release upload ${VERSION} dist/*.{json,gz}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ github.ref_name }}
          MANUAL_VERSION: ${{ github.event.inputs.manual_version }}
          GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
